# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-31 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import freezers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreezerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('device_id', models.CharField(db_index=True, default='0', max_length=20)),
                ('ret', models.TextField(default='')),
                ('source', models.ImageField(max_length=200, upload_to=freezers.models.image_upload_source)),
                ('visual', models.URLField(default='')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('model_id', models.IntegerField()),
                ('type', models.IntegerField(default=0)),
                ('model_path', models.CharField(max_length=200)),
                ('upcs', models.TextField()),
                ('params', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
        migrations.CreateModel(
            name='TrainRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField()),
                ('model_id', models.IntegerField()),
                ('upcs', models.TextField()),
                ('datas', models.TextField()),
                ('pic_cnt', models.IntegerField()),
                ('type', models.IntegerField(default=0)),
                ('model_path', models.CharField(max_length=200)),
                ('params', models.TextField()),
                ('status', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('finish_time', models.DateTimeField()),
                ('accuracy_rate', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='date updated')),
            ],
        ),
    ]
